# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Bmi.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1133, 765)
        MainWindow.setStyleSheet("background-color:rgb(233,232,237);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(120, 160, 901, 421))
        self.frame.setStyleSheet("background-color:rgb(62, 171, 202);\n"
"position:absolute;\n"
"z-index:1;\n"
"border-radius:25px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(60, 100, 351, 51))
        self.lineEdit.setStyleSheet("border-radius:20px;\n"
"border:2px solid white;\n"
"background-color:white;\n"
"position:absolute;\n"
"z-index:2;\n"
"font:18px;\n"
"text-align:center;\n"
"padding:0px 90px 0px 90px;")
        self.lineEdit.setText("")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 170, 351, 51))
        self.lineEdit_2.setStyleSheet("border-radius:20px;\n"
"border:2px solid white;\n"
"background-color:white;\n"
"position:absolute;\n"
"z-index:2;\n"
"font:18px;\n"
"text-align:center;\n"
"padding:0px 90px 0px 90px;")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(70, 280, 331, 61))
        self.pushButton.setStyleSheet("border-radius:20px;\n"
"border:2px solid orange;\n"
"background-color:orange;\n"
"position:absolute;\n"
"z-index:2;\n"
"color:white;\n"
"font-weight:bold;\n"
"font-size:18px;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(610, 340, 241, 41))
        self.pushButton_2.setStyleSheet("border-radius:20px;\n"
"border:2px solid orange;\n"
"background-color:orange;\n"
"position:absolute;\n"
"z-index:2;\n"
"color:white;\n"
"font-weight:bold;\n"
"font: 12pt ;\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(610, 50, 241, 231))
        self.textEdit.setStyleSheet("background-color:rgba(255,255,255,0.7);\n"
"border-radius:70px;")
        self.textEdit.setReadOnly(False)
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame)
        self.textEdit_2.setGeometry(QtCore.QRect(638, 90, 181, 141))
        self.textEdit_2.setStyleSheet("background-color:rgba(255,255,255,0.6);\n"
"border-radius:50px;")
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.voiceicon1 = QtWidgets.QPushButton(self.frame)
        self.voiceicon1.setGeometry(QtCore.QRect(370, 110, 31, 31))
        self.voiceicon1.setStyleSheet("background-color:white;")
        self.voiceicon1.setIcon(QtGui.QIcon("mic.png"))
        self.voiceicon1.setIconSize(QtCore.QSize(60, 60))
        self.voiceicon1.setText("")
        self.voiceicon1.setObjectName("voiceicon1")
        self.voiceicon2 = QtWidgets.QPushButton(self.frame)
        self.voiceicon2.setGeometry(QtCore.QRect(370, 180, 31, 31))
        self.voiceicon2.setStyleSheet("background-color:white;")
        self.voiceicon2.setText("")
        self.voiceicon2.setIcon(QtGui.QIcon("mic.png"))
        self.voiceicon1.setIconSize(QtCore.QSize(60, 60))
        self.voiceicon2.setObjectName("voiceicon2")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(190, 110, 251, 51))
        
        self.lineEdit_6.setStyleSheet("font-size:25px;\n"
"font-weight:bold;\n"
"color:rgb(62, 171, 202);\n"
"background-color:transparent;\n"
"border:0;")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(850, 640, 171, 41))
        self.pushButton_3.setStyleSheet("padding:0px 40px  0px  40px;\n"
"border-radius:15px;\n"
"font-size:19px;\n"
"background-color:rgb(62, 171, 202);\n"
"color:white;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.Logo = QtWidgets.QPushButton(self.centralwidget)
        self.Logo.setGeometry(QtCore.QRect(40, 20, 108, 87))
        self.Logo.setStyleSheet("background-color:transparent;\n"
"border:none")
        self.Logo.setText("")
        self.Logo.setIcon(QtGui.QIcon(r"C:\Users\pushkar\OneDrive\Desktop\icon\Logo.png"))
        self.Logo.setIconSize(QtCore.QSize(102, 85))
        self.Logo.setObjectName("Logo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1133, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter Your Weight"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Enter Your Height"))
        self.pushButton.setText(_translate("MainWindow", "Calculate"))
        self.pushButton_2.setText(_translate("MainWindow", "Book consultation"))
        self.lineEdit_6.setText(_translate("MainWindow", "Smart BMI Chatbot"))
        self.pushButton_3.setText(_translate("MainWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
